revert(pandoc-slides): bump alpine to 3.19
This reverts commit c42926ad7c4dc87409a78a4093b69e8a179b16cf
Failed in CI because

```console
Error: failed to build image components: failed to build
layer image for "arm64": installing apk packages: error
getting package dependencies: could not find package, alias
or a package that provides plantuml in indexes
```

Let's wait `plantuml` successful build in v3.19 branch for
arm64

[skip ci]